name: Integration Test
on:
  workflow_dispatch:
  schedule:
    - cron: "36 20 * * 0"
  pull_request_target:
    types: [labeled]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.label.name }}
  cancel-in-progress: true
jobs:
  integration:
    # Run only on manual, schedule trigger or when 'integration-test' label is added
    if: github.event_name != 'pull_request_target' || github.event.label.name == 'integration-test'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: 'read'
      pull-requests: 'write'
      id-token: 'write'
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
      with:
        workload_identity_provider: projects/195438090918/locations/global/workloadIdentityPools/deck-integration/providers/github
        service_account: deck-integration-test@braided-shift-468913-t8.iam.gserviceaccount.com
    - name: Set up Go
      uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: go.mod
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # v2.1.2
      with:
        chrome-version: stable
    - name: Run integration tests
      env:
        DECK_TEST_FOLDER_ID: '0AIEL8jopnJdRUk9PVA'
        DECK_ENABLE_ADC: "true"
      run: |
        make fulltest
    - name: Run octocov
      uses: k1LoW/octocov-action@b3b6ee60482a667950f87553abf1df63217235d9 # v1.5.1
      with:
        config: .octocov-full.yml
